### ISSUE TITLE
No module named 'examples'

### ISSUE THREAD

**Issue by vanti** [Azure/azure-event-hubs-python#70] opened 2018-10-06 00:07 UTC
I am getting the following error when running the examples:

```
$ python recv.py
Traceback (most recent call last):
  File "recv.py", line 17, in <module>
    import examples
ImportError: No module named 'examples'
```

How do I get the examples module?

**Comment by annatisch** [comment] 2018-10-06 00:36
Thanks @vanti!

Could you try running the sample from the root directory?
```
$ python examples/recv.py
```

**Comment by vanti** [comment] 2018-10-06 00:43
Thanks for the suggestion, @annatisch . Same issue is seen:

$ python examples/recv.py
Traceback (most recent call last):
  File "examples/recv.py", line 17, in <module>
    import examples
ImportError: No module named 'examples'

**Comment by annatisch** [comment] 2018-10-06 00:48
Thanks for the quick feedback @vanti 
I think I'll remove that from the sample... 

In the meantime you can just replace lines 17-18 in the sample with something like this:
```
import logging
logger = logging.getLogger('azure.eventhub')
```

If you want to get more detailed logging of the lower level uAMQP library, take a look at how the logger is configured here:
https://github.com/Azure/azure-event-hubs-python/blob/master/examples/__init__.py

**Comment by vanti** [comment] 2018-10-08 17:29
Thanks! Changing lines 17-18 got me pass that issue.
I now see this error:

```
$ python examples/recv.py
Authentication Put-Token failed. Retries exhausted.
'eventhub.pysdk-1353a556': All clients failed to start.
Traceback (most recent call last):
  File "examples/recv.py", line 39, in <module>
    client.run()
  File "/home/a0792201local/workdir/azure/azureenv3/lib/python3.4/site-packages/azure/eventhub/client.py", line 277, in run
    raise failed[0]
azure.eventhub.common.EventHubError: CBS Token authentication failed.
Status code: 401
Description: b'The specified SAS token has an invalid signature. It does not match either the primary or secondary key.'

```

I have set the following environment variables, based on the settings from my IoT Hub (shown with red boxes in the screenshot):

EVENT_HUB_ADDRESS=amqps://(ub).azure-devices.net/myeventhub
EVENT_HUB_SAS_POLICY=service
EVENT_HUB_SAS_POLICY=(primary key of service policy)

Is there anything I am doing incorrectly? Wished there was more documentation on this.

![service policy](https://user-images.githubusercontent.com/1307572/46624091-a8507700-cae4-11e8-8597-5cfa071de186.jpg)

**Comment by annatisch** [comment] 2018-10-08 17:36
Thanks @vanti 
Aaaah I see you're connecting to an IoT Hub rather than directly to EventHub.
In this case the set up is a little different.

While I don't have a sample for it - you can see a code snippet for it in my test here:
https://github.com/Azure/azure-event-hubs-python/blob/master/tests/test_iothub_receive.py

In this case, it's best to use the connection string rather than the separate policy/key fields as we have to do some manipulation of the Iot Hub endpoint in order to get the endpiont of the underlying Event Hub.

Let me know how it goes!

There's also an extended conversation on IoT Hub support in an early issue in case it provides a bit more context:
https://github.com/Azure/azure-event-hubs-python/issues/28

**Comment by vanti** [comment] 2018-10-08 19:12
Thanks for the snippet, @annatisch. I created the attached "sample", but it gives me an error:

```
$ python iothub_recv.py 
Authentication Put-Token failed. Retries exhausted.
Traceback (most recent call last):
  File "iothub_receive.py", line 39, in <module>
    test_iothub_receive_sync(CONNSTR, 0)
  File "iothub_receive.py", line 30, in test_iothub_receive_sync
    partitions = client.get_eventhub_info()
  File "/home/a0792201local/workdir/azure/azureenv3/lib/python3.4/site-packages/azure/eventhub/client.py", line 323, in get_eventhub_info
    description_fields=b'status-description')
  File "/home/a0792201local/workdir/azure/azureenv3/lib/python3.4/site-packages/uamqp/client.py", line 307, in mgmt_request
    timeout, auth_in_progress = self._auth.handle_token()
  File "/home/a0792201local/workdir/azure/azureenv3/lib/python3.4/site-packages/uamqp/authentication/cbs_auth.py", line 129, in handle_token
    raise errors.TokenAuthFailure(*self._cbs_auth.get_failure_info())
uamqp.errors.TokenAuthFailure: CBS Token authentication failed.
Status code: 401
Description: b'The specified SAS token has an invalid signature. It does not match either the primary or secondary key.'
```

I copied the connection string directly from my IoT Hub's service policy. Is this how the feature is supposed to work?

[iothub_recv.zip](https://github.com/Azure/azure-event-hubs-python/files/2457342/iothub_recv.zip)

**Comment by annatisch** [comment] 2018-10-08 20:36
Thanks @vanti - I tried your attached sample substituting my own IotHub connection string and I was able to reproduce it running on a linux container.

I'm detecting two different errors here - the first is the same one you described. This is intermittent, and is happening when the client determines that the connection is stable when in fact the service should be sending a detach/redirect message. This seems to be an issue with timing that I will take a closer look at.
Do you get this error consistently? If you run the script 10 times you get the same error each time?

The other error I get seems to be specific to running the client in Python 3.4 on linux (I've also tested in 3.4 on Windows and 3.6 on Linux - which worked okay) and it is a segmentation fault when attempting to retrieve the EventHub partition info (line 30 of your attached sample).


Sorry for issues getting this sample running - I will update the thread with my findings as soon as possible!

**Comment by vanti** [comment] 2018-10-08 20:58
You are right, the previous error message was more common, but if I try to run it several times, it'd sometimes give me this alternate error message (I modified the credentials):

```
$ python iothub_receive.py 
LinkRedirect('ErrorCodes.LinkRedirect',)
Traceback (most recent call last):
  File "/home/local/workdir/azure/azureenv3/lib/python3.4/site-packages/uamqp/authentication/cbs_auth.py", line 82, in create_authenticator
    self._connection.container_id)
  File "./src/cbs.pyx", line 71, in uamqp.c_uamqp.CBSTokenAuth.__cinit__
ValueError: Unable to open CBS link.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/local/workdir/azure/azureenv3/lib/python3.4/site-packages/azure/eventhub/client.py", line 281, in run
    self._handle_redirect(redirects)
  File "/home/local/workdir/azure/azureenv3/lib/python3.4/site-packages/azure/eventhub/client.py", line 256, in _handle_redirect
    client.open()
  File "/home/local/workdir/azure/azureenv3/lib/python3.4/site-packages/azure/eventhub/receiver.py", line 99, in open
    self._handler.open()
  File "/home/local/workdir/azure/azureenv3/lib/python3.4/site-packages/uamqp/client.py", line 234, in open
    debug=self._debug_trace)
  File "/home/local/workdir/azure/azureenv3/lib/python3.4/site-packages/uamqp/authentication/cbs_auth.py", line 88, in create_authenticator
    "Please confirm target hostname exists: {}".format(connection.container_id, connection.hostname))
uamqp.errors.AMQPConnectionError: Unable to open authentication session on connection b'EHReceiver-ff5c815b-5405-40d5-a815-f5860077a4fe-partition0'.
Please confirm target hostname exists: b'iothub-ns-ub-173602-8d17938640.servicebus.windows.net'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "iothub_receive.py", line 40, in <module>
    test_iothub_receive_sync(CONNSTR, 0)
  File "iothub_receive.py", line 30, in test_iothub_receive_sync
    client.run()
  File "/home/local/workdir/azure/azureenv3/lib/python3.4/site-packages/azure/eventhub/client.py", line 287, in run
    raise EventHubError(str(e))
azure.eventhub.common.EventHubError: Unable to open authentication session on connection b'EHReceiver-ff5c815b-5405-40d5-a815-f5860077a4fe-partition0'.
Please confirm target hostname exists: b'iothub-ns-ub-173602-8d17938640.servicebus.windows.net'
```

**Comment by annatisch** [comment] 2018-10-09 17:37
Hi @vanti 

I have found a fix to the "timing" issue around redirecting the IoTHub connection that results in the `"SAS token has an invalid signature"` error. Unfortunately it requires a change to the underlying C library. I will PR the fix today, then publish the updates to uAMQP Python - then it will finally be available for the EventHubs Python SDK. I will track the progress here.

On the other hand - this shouldn't be causing the "Please confirm target hostname exists" error.
I wonder if this is a permissions issue - could you try running the script using the "iothubowner" connection string?

**Comment by annatisch** [comment] 2018-10-09 19:42
I have open a PR to the C library here:
https://github.com/Azure/azure-uamqp-c/pull/261

**Comment by vanti** [comment] 2018-10-09 22:58
Thanks for the update @annatisch. Using the "iothubowner" connection string gives the same error. Do you know if the target hostname "iothub-ns-ub-173602-8d17938640.servicebus.windows.net" is supposed to be pingable? It doesn't seem to be the case for me.

**Comment by annatisch** [comment] 2018-10-10 22:54
Thanks @vanti - hmm I'm not sure if the target will be pingable - another thing you could try to confirm whether there's any other issues connecting to the endpoint, is to try the process I documented in this issue here:
https://github.com/Azure/azure-event-hubs-python/issues/28#issuecomment-385069819

Effectively, from the portal, try the "operations monitoring" endpoint, and pass it into the normal "create_from_connection_str" constructure (rather than the IotHub specific one) along with your IotHub name.  This was the recommended approach before we adapted the SDK to reach the IoTHub endpoint directly - but maybe worth a try in this case :)

**Comment by vanti** [comment] 2018-10-11 20:49
@annatisch - Our company needs to setup a proxy plug to allow us to access 'iothub-ns-ub-173602-8d17938640.servicebus.windows.net' over AMQP from within our internal network. Do you know if this hostname changes over time? We want to avoid having to constantly contact IT if possible.

I tried the script outside the company firewall and only saw the "SAS token has an invalid signature" error.

**Comment by annatisch** [comment] 2018-10-11 21:01
Thanks @vanti - that's a very good question - adding in some IoT experts who can hopefully shed some light on that.

@digimaun, @pierreca - are you able to verify whether the IotHub redirected EventHub hostname will remain consistent for the life of the IoTHub?

**Comment by pierreca** [comment] 2018-10-12 02:29
@annatisch thanks for the tag
@vanti thanks for the question. I talked to the service team and the only time the event hubs endpoint can change is in case of failover (something bad happened to the datacenter and Microsoft is migrating the hub (or you in case of manual failover)).

WRT proxy settings, maybe if you support wildcards you could have something that lets iothub-ns*.servicebus.windows.net through it?

**Comment by pierreca** [comment] 2018-10-12 18:19
@vanti it should be extremely rare, probably on the order of years, but it can just happen. we're talking about catastrophic-level event.

given all event hubs follow that naming pattern, this wildcard would be sufficient. 

Another thing you could do would be to use custom routing rules and route all messages to 2 hubs on 2 different regions, and then manually handle reading from one or the other depending on availability. that way you could whitelist only those event hubs and not worry about failover, given the new hub would restore the routes to both these hubs, and it's unlikely that 2 different regions would be affected by the same disaster.

**Comment by vanti** [comment] 2018-10-15 21:27
Thanks @pierreca. Good to know that it is not a common occurrence. Unfortunately our IT department is unable to support the wildcard, so we'll deal with the failout when it comes.

@annatisch After setting up the proxy plug, I no longer see the target hostname error. I am now mostly seeing the "SAS token has an invalid signature" error, and sometimes the following:

```
LinkRedirect('ErrorCodes.LinkRedirect',)
Traceback (most recent call last):
  File "iothub_receive.py", line 42, in <module>
    test_iothub_receive_sync(CONNSTR, 0)
  File "iothub_receive.py", line 32, in test_iothub_receive_sync
    client.run()        
  File "/home/local/workdir/azure/azureenv3/lib/python3.4/site-packages/azure/eventhub/client.py", line 281, in run
    self._handle_redirect(redirects)
  File "/home/local/workdir/azure/azureenv3/lib/python3.4/site-packages/azure/eventhub/client.py", line 256, in _handle_redirect
    client.open()
  File "/home/local/workdir/azure/azureenv3/lib/python3.4/site-packages/azure/eventhub/receiver.py", line 100, in open
    while not self.has_started():
  File "/home/local/workdir/azure/azureenv3/lib/python3.4/site-packages/azure/eventhub/receiver.py", line 172, in has_started
    raise EventHubError("Authorization timeout.")
azure.eventhub.common.EventHubError: Authorization timeout.
```

**Comment by annatisch** [comment] 2018-10-15 21:43
Thanks @vanti!
These should be resolved with the next release of uAMQP which I hope to publish this week.

**Comment by annatisch** [comment] 2018-10-19 14:44
Hi @vanti - thanks for your patience!
I have published a preliminary fix in [uAMQP RC2](https://github.com/Azure/azure-uamqp-python/releases/tag/v1.1.0rc2) - if you update your uamqp installation this will hopefully resolve the "Please confirm target hostname exists" error.
```
pip install --upgrade uamqp==1.1.0rc2
```

**Comment by vanti** [comment] 2018-11-07 19:32
Hi @annatisch, sorry for the delay. I updated my uamqp installation as you described above, and now it gives me a different error:

> $ python iothub_receive.py
> 'eventhub.pysdk-3a6ccc59': All clients failed to start.
> Traceback (most recent call last):
>   File "iothub_receive.py", line 42, in <module>
>     test_iothub_receive_sync(CONNSTR, 0)
>   File "iothub_receive.py", line 32, in test_iothub_receive_sync
>     client.run()        
>   File "/home/a0792201local/workdir/azure/azureenv3/lib/python3.4/site-packages/azure/eventhub/client.py", line 277, in run
>     raise failed[0]
> azure.eventhub.common.EventHubError: Failed to open Message Receiver. Please confirm credentials and target URI.

**Comment by vanti** [comment] 2018-11-07 19:34
Hi @annatisch, sorry for the delay. I updated uamqp as you described above, and am now getting a different error:

```
$ python iothub_receive.py
'eventhub.pysdk-3a6ccc59': All clients failed to start.
Traceback (most recent call last):
  File "iothub_receive.py", line 42, in <module>
    test_iothub_receive_sync(CONNSTR, 0)
  File "iothub_receive.py", line 32, in test_iothub_receive_sync
    client.run()        
  File "/home/local/workdir/azure/azureenv3/lib/python3.4/site-packages/azure/eventhub/client.py", line 277, in run
    raise failed[0]
azure.eventhub.common.EventHubError: Failed to open Message Receiver. Please confirm credentials and target URI.
```

**Comment by annatisch** [comment] 2018-11-09 20:49
Thanks @vanti - please see my response to issue #77 with regards to the LinkStolen error.
The error opening message receiver is still strange - I have an new release going out next week.

Once I have that under way I will try to repro this again. 
Thanks for the update!

**Comment by to175** [comment] 2019-02-01 11:53
> Hi @vanti - thanks for your patience!
> I have published a preliminary fix in [uAMQP RC2](https://github.com/Azure/azure-uamqp-python/releases/tag/v1.1.0rc2) - if you update your uamqp installation this will hopefully resolve the "Please confirm target hostname exists" error.
> 
> ```
> pip install --upgrade uamqp==1.1.0rc2
> ```

Hello,
I got this error : [pic](https://image.noelshack.com/fichiers/2019/05/5/1549021905-capture.png)
I cant upgrade... help please.

I have still this error (I have put "xxx" to hide info) :
`EventHubError: Unable to open authentication session on connection b'EHSender-xxx-xxx-xxx-xxx-xxx-partition0'.
Please confirm target hostname exists: b'xxx.servicebus.windows.net'`

**Closed** 2019-05-17 22:46 UTC
