### ISSUE TITLE
Messages received by multiple instances

### ISSUE THREAD

**Issue by konstantinmiller** [Azure/azure-event-hubs-python#85] opened 2018-12-17 16:38 UTC
I am seeing multiple instances of the event processor host receiving the same messages sometimes. Is it intended behavior, or should the epoch parameter not actually prevent that from happening?

**Comment by annatisch** [comment] 2018-12-17 16:43
Thanks @konstantinmiller,
This is likely intended behaviour - when an EventHub event is processed - it is not removed from the event hub until it eventually expires (~ a week depending on configuration).

In this case you will want to set an offset value, and keep track of the Sequence Numbers of the events as you receive them so that if you wish to stop and start receiving, you can pass in the offset value to pick up where you left of with out duplicate processing.
You can see more details on Offset here:
https://docs.microsoft.com/en-us/python/api/azure-eventhub/azure.eventhub.common.offset?view=azure-python

The Epoch setting is slightly different and is used to ensure only a single receiver is processing a stream of messages from a single partition/consumer group. This ensures that an event is only processed by a single consumer.

Let me know if this helps :)

**Comment by konstantinmiller** [comment] 2018-12-17 22:15
Hi @annatisch,

Sorry, it was my fault, I was too imprecise.

I am aware of the offset and sequence numbers. What we are doing is, we are running an EventProcessorHost in Kubernetes, and what we observe is, that during upscaling, that is when new pods are created, some pods are receiving duplicated messages. 

I am aware of the lease mechanism and that instances can steal leases from each other. And that the instance whose instance gets stolen, only notices that when it tries to renew the lease.

Meanwhile, should it be possible that the old instance and the new instance are receiving the same messages? Or is the EventProcessorHost using the epoch mechanisms to prevent this from happening?

**Comment by konstantinmiller** [comment] 2019-04-05 14:04
Hi @annatisch ,

Is the EPH designed to prevent multiple instances from processing the same messages in parallel? Or can this happen during certain periods of time, e.g. during upscaling?

**Comment by annatisch** [comment] 2019-04-05 15:43
Thanks @konstantinmiller - sorry for the delay.

@xinchen10 - can you please confirm whether this is the case?

> Is the EPH designed to prevent multiple instances from processing the same messages in parallel? Or can this happen during certain periods of time, e.g. during upscaling?

**Comment by JamesBirdsall** [comment] 2019-04-06 01:55
EPH uses epoch receivers, but those cannot completely prevent reprocessing of events. Let's consider the upscaling scenario:

* Host A is processing events for partition 0. It gets a big batch and starts processing.
* Host B comes online and steals partition 0. It creates a receiver with a higher epoch, which disconnects host A's receiver on partition 0.
* Host A is still processing the batch that it already has. It cannot receive more events because its receiver has been disconnected, but it will not find out about that until it finishes the batch and makes a receive call.
* Host B's receiver starts from the last checkpointed position, which will depend on how often the application code checkpoints. Since host A is still working on the batch, the checkpoint is either at the end of the last batch or somewhere in this batch, so host B gets some events that host A is also processing.
* Host A reaches the end of the batch. If the lease renewer has fired, then it already knows that it has lost the lease for partition 0. Otherwise, it tries to receive more events and gets an exception because its receiver has been disconnected. Either way, host A shuts down processing for partition 0.

In practice, this is less of a problem than it sounds like, because a consuming application that is keeping up with event flow will be receiving very small batches, frequently only one event at a time.

In general, applications must be able to detect or tolerate the reprocessing of events to some degree. A batch size of 1 and checkpointing after every event makes the window as small as possible (and is not recommended due to the performance hit!), but even then the application could crash after the event is processed but before the checkpoint is written.

**Comment by annatisch** [comment] 2019-04-08 14:41
Thanks @JamesBirdsall!
Closing this issue as this appears to be by design.

**Closed by annatisch** 2019-04-08 14:41 UTC
