### ISSUE TITLE
Eventhub receiver not working after an upgrade to release 0.2.0rc2 

### ISSUE THREAD

**Issue by nimonika** [Azure/azure-event-hubs-python#52] opened 2018-08-07 09:44 UTC
The receiver throws
```
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

**Comment by annatisch** [comment] 2018-08-07 14:58
Thanks @nimonika - can I ask which version of uamqp you have installed?
Additionally if you have a code snippet that reproduces this - along with other details such as OS, Python versions etc that would be great.

**Comment by annatisch** [comment] 2018-08-07 15:01
A couple more questions:
- are you running the receiver synchronously or asynchronously?
- are you running more than one receiver concurrently?
- if so, against how many partitions?

**Comment by nimonika** [comment] 2018-08-07 15:39
The uamqp version is 0.2.0. The Python version is 3.6. The OS is Mac OSX. We are running 1 receiver synchronously against 1 partition. 
```
receiver = self.client.add_receiver(self.consumer_group,
                                                self.partition,
                                                prefetch=self.prefetch,
                                                offset=Offset(offset))
            self.client.run()
            logger.info('receiver from {} started'.format(offset))
            while True:
                events = receiver.receive(max_batch_size=self.max_batch_size)
                for event in events:
                    yield str(event.message), event.offset.value
```

**Comment by annatisch** [comment] 2018-08-07 15:41
Thanks @nimonika - at what point is the client crashing?

**Comment by nimonika** [comment] 2018-08-07 15:43
It crashes quite randomly, there seems to be no pattern, however it happens approximately after 50 - 55 minutes, once the client starts receiving

**Comment by annatisch** [comment] 2018-08-07 16:00
Thanks @nimonika - I've published a new uAMQP version (0.2.1) this morning and I'm publishing a new azure-eventhub verison today as well.

The updates include a couple of minor bug fixes - so it will be interesting to see if this resolves it. Otherwise I think we should attach a logger to try see what's happening at the time of the crash :)

**Comment by annatisch** [comment] 2018-08-07 17:57
Hi @nimonika - I've just published azure-eventhub 0.2.0 - would be great to hear if you still encounter the same error.
Interesting that it's happening approximately 50-55 minutes in - as this is when the CBS token is refreshed, so it's very possible something is going wrong with authentication.

It would be great to add a logger to the receiver, the logger I use for debugging looks like this:
```
import sys
import logging
from logging.handlers import RotatingFileHandler

def get_logger(filename, level=logging.INFO):
    azure_logger = logging.getLogger("azure")
    azure_logger.setLevel(level)
    uamqp_logger = logging.getLogger("uamqp")
    uamqp_logger.setLevel(logging.INFO)

    formatter = logging.Formatter('%(asctime)s %(name)-12s %(levelname)-8s %(message)s')
    file_handler = RotatingFileHandler(filename, maxBytes=3*1024*1024, backupCount=2)
    file_handler.setFormatter(formatter)
    azure_logger.addHandler(file_handler)
    uamqp_logger.addHandler(file_handler)

    return azure_logger

logger = get_logger("eh_log.txt", logging.DEBUG)
```

**Comment by nimonika** [comment] 2018-08-08 12:55
@annatisch I upgraded to the new libraries and it appear that the error is indeed related to authorisation
```
Traceback (most recent call last):
  File "/Users/monika/AgrimetricsGitHub/agrimetrics-backend/env/lib/python3.6/site-packages/azure/eventhub/receiver.py", line 209, in receive
    timeout=timeout_ms)
  File "/Users/monika/AgrimetricsGitHub/agrimetrics-backend/env/lib/python3.6/site-packages/uamqp/client.py", line 967, in receive_message_batch
    receiving = self.do_work()
  File "/Users/monika/AgrimetricsGitHub/agrimetrics-backend/env/lib/python3.6/site-packages/uamqp/client.py", line 340, in do_work
    raise TimeoutError("Authorization timeout.")
TimeoutError: Authorization timeout.
```

**Comment by annatisch** [comment] 2018-08-08 14:05
Interesting that you're encountering a timeout - we currently allow for 60 seconds for a token to be authenticated.
Approximately how long does it take the client to process a batch of messages?
What value are you currently setting to prefetch?

And late question - since installing the new release - is the client still crashing (SIGSEGV)? Or is it raising this error normally and closing?

**Comment by annatisch** [comment] 2018-08-08 14:12
If you want to try a quick fix - try setting the timeout value here to 0 (i.e. no timeout):
https://github.com/Azure/azure-event-hubs-python/blob/master/azure/eventhub/client.py#L179

If that works then it genuinely does need longer - so I will make the auth timeout a configurable option.

**Comment by nimonika** [comment] 2018-08-08 14:16
We have not specified a batch size, the prefetch is set to 300. The client still runs for approximately 55 minutes. I have only run the client once and it exited with an error code of 1.

**Comment by nimonika** [comment] 2018-08-08 15:42
I made the changes as suggested above and it seems to be working so far, however I will only know for sure when the client has run for a couple of hours

**Comment by annatisch** [comment] 2018-08-08 15:44
Great! Let me know how it goes :)
I've made the change to expose the authentication timeout for configuration so I will release that maybe at the end of the week :)

**Comment by annatisch** [comment] 2018-08-10 13:54
Hi @nimonika - any updates?

**Comment by nimonika** [comment] 2018-08-10 15:01
Hi @annatisch I did not run the job to completion, but I did run it for a long while and it ran without any errors.

**Comment by annatisch** [comment] 2018-08-10 15:03
Thanks @nimonika! I will close this for now - please re-open if the issue re-surfaces.
I will soon be publishing an update that allows the auth timeout to be configured or disabled.

**Closed by annatisch** 2018-08-10 15:03 UTC
Labels: bug
